// <auto-generated />
using System;
using ExamenPOO2.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenPOO2.API.Migrations
{
    [DbContext(typeof(ExamenPOOContext))]
    [Migration("20240727012607_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamenPOO2.API.Database.Entities.AmortizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Days")
                        .HasColumnType("int")
                        .HasColumnName("days");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int")
                        .HasColumnName("installment_number");

                    b.Property<int>("Interest")
                        .HasColumnType("int")
                        .HasColumnName("interest");

                    b.Property<int>("LevelPaymentWithSVSD")
                        .HasColumnType("int")
                        .HasColumnName("levelpayment_with_SVSD");

                    b.Property<int>("LevelPaymentWithoutSVSD")
                        .HasColumnType("int")
                        .HasColumnName("levelpayment_without_SVSD");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date");

                    b.Property<int>("Principal")
                        .HasColumnType("int")
                        .HasColumnName("principal");

                    b.Property<int>("PrincipalBalance")
                        .HasColumnType("int")
                        .HasColumnName("principal_balance");

                    b.HasKey("Id");

                    b.ToTable("amortizations", "dbo");
                });

            modelBuilder.Entity("ExamenPOO2.API.Database.Entities.ClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("clients", "dbo");
                });

            modelBuilder.Entity("ExamenPOO2.API.Database.Entities.LoanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("CommissionRate")
                        .HasColumnType("int")
                        .HasColumnName("commission_rate");

                    b.Property<DateTime>("DisbursementDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("disbursement_date");

                    b.Property<DateTime>("FirstPaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("first_payment_date");

                    b.Property<int>("IdentityNumber")
                        .HasColumnType("int")
                        .HasColumnName("identity_number");

                    b.Property<int>("InterestRate")
                        .HasColumnType("int")
                        .HasColumnName("interest_rate");

                    b.Property<int>("LoanAmount")
                        .HasColumnType("int")
                        .HasColumnName("loan_amount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Term")
                        .HasColumnType("int")
                        .HasColumnName("term");

                    b.HasKey("Id");

                    b.ToTable("loans", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
