// <auto-generated />
using System;
using ExamenPOO2.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenPOO2.API.Migrations
{
    [DbContext(typeof(ExamenPOOContext))]
    partial class ExamenPOOContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamenPOO2.API.Database.Entities.AmortizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Days")
                        .HasColumnType("int")
                        .HasColumnName("days");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int")
                        .HasColumnName("installment_number");

                    b.Property<double>("Interest")
                        .HasColumnType("float")
                        .HasColumnName("interest");

                    b.Property<double>("LevelPaymentWithSVSD")
                        .HasColumnType("float")
                        .HasColumnName("levelpayment_with_SVSD");

                    b.Property<double>("LevelPaymentWithoutSVSD")
                        .HasColumnType("float")
                        .HasColumnName("levelpayment_without_SVSD");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loan_id");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date");

                    b.Property<double>("Principal")
                        .HasColumnType("float")
                        .HasColumnName("principal");

                    b.Property<double>("PrincipalBalance")
                        .HasColumnType("float")
                        .HasColumnName("principal_balance");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("amortizations", "dbo");
                });

            modelBuilder.Entity("ExamenPOO2.API.Database.Entities.ClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("identify_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("clients", "dbo");
                });

            modelBuilder.Entity("ExamenPOO2.API.Database.Entities.LoanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("client_id");

                    b.Property<double>("CommissionRate")
                        .HasColumnType("float")
                        .HasColumnName("commission_rate");

                    b.Property<DateTime>("DisbursementDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("disbursement_date");

                    b.Property<DateTime>("FirstPaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("first_payment_date");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float")
                        .HasColumnName("interest_rate");

                    b.Property<double>("LoanAmount")
                        .HasColumnType("float")
                        .HasColumnName("loan_amount");

                    b.Property<int>("Term")
                        .HasColumnType("int")
                        .HasColumnName("term");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("loans", "dbo");
                });

            modelBuilder.Entity("ExamenPOO2.API.Database.Entities.AmortizationEntity", b =>
                {
                    b.HasOne("ExamenPOO2.API.Database.Entities.LoanEntity", "Loan")
                        .WithMany("AmortizationPlan")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("ExamenPOO2.API.Database.Entities.LoanEntity", b =>
                {
                    b.HasOne("ExamenPOO2.API.Database.Entities.ClientEntity", "Client")
                        .WithMany("Loans")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ExamenPOO2.API.Database.Entities.ClientEntity", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("ExamenPOO2.API.Database.Entities.LoanEntity", b =>
                {
                    b.Navigation("AmortizationPlan");
                });
#pragma warning restore 612, 618
        }
    }
}
